### ISSUE TITLE
issue #1

### ISSUE THREAD

**Issue by danilamaroz** [danilamaroz/BVAR.jl#1]
XXX = Array(Float64, 5)
for i in 1:30
  XXX[i] = zeros(Float64, 4)
end

**Comment by danilamaroz** [comment]
also a more general question: is it possible to store heterogeneous data in one object (equivalent of dataframe in R)?

**Comment by gragusa** [comment]
```
julia> X = Array(Float64, 5)
5-element Array{Float64,1}:
 1.96872e-153
 5.27365e-91
 1.08823e-71
 6.59188e-259
 0.0
```

`X` is an array of dimension `5`. You can assign to it five elements. 

```
for j = 1:5
   X[i] = 0.0
end
```

or 

```
for j = 1:5
   X[i] = zero(Float64)
end
```

If you assign `zeros(Float64, 4)` to `X[i]` you are assigning an array of dimension 4 to a singleton.

**Comment by gragusa** [comment]
There is a package for this: [Dataframes.jl](https://github.com/JuliaStats/DataFrames.jl)
